<a href="https://colab.research.google.com/github/sanah-imani/DrugDisc/blob/master/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from chembl_webresource_client.new_client import new_client

drug_indication = new_client.drug_indication
molecules = new_client.molecule
lung_cancer_ind = drug_indication.filter(efo_term__icontains="LUNG CARCINOMA")
lung_cancer_mols = molecules.filter(molecule_chembl_id__in=[x['molecule_chembl_id'] for x in lung_cancer_ind])

/usr/local/lib/python3.6/dist-packages/grequests.py:21: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.contrib.pyopenssl (/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py)', 'urllib3.util (/usr/local/lib/python3.6/dist-packages/urllib3/util/__init__.py)'].
  curious_george.patch_all(thread=False, select=False)

In [0]:
import matplotlib.pyplot as plt

from sklearn import svm
from sklearn.cross_validation import train_test_split
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [0]:
from chembl_webresource_client.new_client import new_client
drug_indication = new_client.drug_indication
molecules = new_client.molecule
ovary_cancer_ind = drug_indication.filter(efo_term__icontains="OVARIAN NEOPLASM")
ovary_cancer_mols = molecules.filter(molecule_chembl_id__in=[x['molecule_chembl_id'] for x in ovary_cancer_ind])

In [0]:
import pandas as pd



    
arr = ovary_cancer_mols[0]['molecule_properties']

for i in range(0,1):
    arr['max_phase'] = ovary_cancer_mols[i]['max_phase']
arr['active'] = 0
arr_labels = []
for key in arr.keys():
    arr_labels.append(key)
a = []
for i in range(24):
    a.append([])   
    


for q in range(0,24):
    a[q].append(arr[arr_labels[q]])
    


index2 = []
for p in range(1,15):
    count = 1
    list1 = ovary_cancer_mols[p]['molecule_properties']
    if ovary_cancer_mols[p]['max_phase'] == None:
        ovary_cancer_mols[p]['max_phase'] = float('nan')
        
    list1['max_phase'] = ovary_cancer_mols[p]['max_phase']
    list1['active'] = 0
    for j in range(0,24):
        a[j].append(list1[arr_labels[j]])
    count += 1


def makeDict(list1, list2):
    new_Dict = {}
    for i in range(0,24):
        new_Dict[list1[i]] = list2[i]
    return new_Dict

for i in range(31, 31 + 15):
    index2.append(i)
   
data3 = pd.DataFrame(data = makeDict(arr_labels, a), index = index2)
data3 = data3[arr_labels]
data3.head()

,acd_logd,acd_logp,acd_most_apka,acd_most_bpka,alogp,aromatic_rings,full_molformula,full_mwt,hba,hba_lipinski,...,mw_freebase,mw_monoisotopic,num_lipinski_ro5_violations,num_ro5_violations,psa,qed_weighted,ro3_pass,rtb,max_phase,active
31,-1.68,1.4,3.48,None,1.31,1.0,C9H8O4,180.16,3.0,4.0,...,180.16,180.0423,0.0,0.0,63.6,0.55,N,2.0,4,0
32,-0.32,0.32,8.92,7.65,1.85,3.0,C23H23N3O5,421.45,8.0,8.0,...,421.45,421.1638,0.0,0.0,104.89,0.49,N,3.0,4,0
33,3.95,3.95,11.9,None,3.74,3.0,C47H51NO14,853.92,14.0,15.0,...,853.92,853.331,2.0,2.0,221.29,0.13,N,10.0,4,0
34,None,None,None,None,None,NaN,H6Cl2N2Pt+2,300.05,NaN,NaN,...,300.05,298.9545,NaN,NaN,None,None,None,NaN,4,0
35,2.34,2.34,9.48,0.5,2.47,1.0,C14H20N2O3,264.32,3.0,5.0,...,264.32,264.1474,0.0,0.0,78.43,0.38,N,8.0,4,0

In [0]:
import pandas as pd



    
arr = lung_cancer_mols[0]['molecule_properties']
for i in range(0,1):
    arr['max_phase'] = lung_cancer_mols[i]['max_phase']
arr['active'] = 1
arr_labels = []
for key in arr.keys():
    arr_labels.append(key)
a = []
for i in range(24):
    a.append([])   
    


for q in range(0,24):
    a[q].append(arr[arr_labels[q]])
    


index = []
for p in range(1,30):
    count = 1
    list1 = lung_cancer_mols[p]['molecule_properties']
    list1['max_phase'] = lung_cancer_mols[p]['max_phase']
    list1['active'] = 1
    for j in range(0,24):
        a[j].append(list1[arr_labels[j]])
    count += 1


def makeDict(list1, list2):
    new_Dict = {}
    for i in range(0,24):
        new_Dict[list1[i]] = list2[i]
    return new_Dict
for i in range(1,31):
    index.append(i)

data2 = pd.DataFrame(data = makeDict(arr_labels, a),index = index, copy = True)
data2 = data2[arr_labels]
data2.head()

,acd_logd,acd_logp,acd_most_apka,acd_most_bpka,alogp,aromatic_rings,full_molformula,full_mwt,hba,hba_lipinski,...,mw_freebase,mw_monoisotopic,num_lipinski_ro5_violations,num_ro5_violations,psa,qed_weighted,ro3_pass,rtb,max_phase,active
1,-0.62,0.57,None,8,1.85,1.0,C10H14N2,162.24,2.0,2.0,...,162.24,162.1157,0.0,0.0,16.13,0.63,Y,1.0,4,1
2,5.88,5.88,9.98,1.55,6.86,1.0,C26H33NO2,391.56,2.0,3.0,...,391.56,391.2511,1.0,1.0,49.33,0.32,N,6.0,3,1
3,4.26,4.26,10.4,None,6.18,0.0,C51H79NO13,914.19,13.0,14.0,...,914.19,913.5551,3.0,3.0,195.43,0.16,N,6.0,4,1
4,-1.47,0.24,7.35,8.68,0,2.0,C27H29NO11,543.53,12.0,12.0,...,543.53,543.1741,3.0,3.0,206.07,0.24,N,5.0,4,1
5,-1.68,1.4,3.48,None,1.31,1.0,C9H8O4,180.16,3.0,4.0,...,180.16,180.0423,0.0,0.0,63.6,0.55,N,2.0,4,1

In [0]:
data2 = pd.DataFrame(data = makeDict(arr_labels, a),index = index)

In [0]:
data2 = data2.append(data3)
print(len(data2))
data2.drop(labels = ['max_phase', 'full_molformula'],axis = 1,inplace= True)
data2['molecular_species'].replace(to_replace=['NEUTRAL'], value = 0.5, inplace = True)
data2['molecular_species'].replace(to_replace=['BASE'], value = 1,inplace=True)
data2['ro3_pass'].replace(to_replace=['Y'], value = 1,inplace=True)
data2['ro3_pass'].replace(to_replace = ['N'], value = 0, inplace=True)
data2['molecular_species'].replace(to_replace=['ACID'], value = 0,inplace=True)
data2 = data2.apply(pd.to_numeric, errors = 'ignore')

y = data2['active'].values

data2.drop(labels = ['active'],axis = 1,inplace= True)
X = data2.iloc[::].values

print(len(X[0]))

45
21

In [0]:
from statistics import median
import numpy as np
import math
for i in range(0,45):
    for j in range(0, len(X[i])):
        lst = []
        if math.isnan(X[i][j]):
            for b in range(0,45):
                if math.isnan(X[b][j]) == False:
                    
                    lst.append(X[b][j])
            X[i][j] = median(lst)
            
for i in range(0,45):
    for j in range(0, len(X[i])):
        X[i][j] = np.float32(X[i][j])
def median(lst):
    sortedLst = sorted(lst)
    lstLen = len(lst)
    index = (lstLen - 1) // 2

    if (lstLen % 2):
        return sortedLst[index]
    else:
        return (sortedLst[index] + sortedLst[index + 1])/2.0

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [0]:
clf = svm.SVC(C = 1000)

clf.fit(X_train,y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
pred = clf.predict(X_test)

real = y_test

count = 0

for i in range(len(pred)):
    if pred[i] == real[i]:
        count = count + 1

In [0]:
pred

In [0]:
real